.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013 Mats Sjöberg <mats@sjoberg.fi>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PUMPA 1 "December 16, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pumpa \- Pumpa is a simple desktop client for pump.io.
.SH SYNOPSIS
.B pumpa
.OP \-c alternative.conf
.OP \-l locale
.br
.B pumpa -h
.SH DESCRIPTION
Pumpa is a simple Qt desktop client for identi.ca and other
pump.io-based federated social network services.
.SH OPTIONS
A summary of options is included below.
.TP
\-h, \-\-help
Show summary of options.
.IP "\-c \fIalternative.conf\fR"
Use \fIalternative.conf\fR instead of the standard configuration file.
.TP
.IP "\-l \fIlocale\fR"
Set locale to \fIlocale\fR (e.g. es, en_GB) instead of the
auto-detected locale.
.SH AUTHOR
Pumpa was written by Mats Sjöberg <mats@sjoberg.fi>
